name: Unpublish Extension

on:
  workflow_dispatch:
    inputs:
      extension-id:
        required: true
        default: 'alloglot'

jobs:
  unpublish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Set up Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: '16'

    - name: Install vsce
      run: npm install -g vsce

    - name: Authenticate with Personal Access Token (PAT)
      env:
        VSCE_PAT: ${{ secrets.MARKETPLACE_TOKEN}}
      run: |
        if [ -z "$VSCE_PAT" ]; then
          echo "VSCE_PAT secret is not set. Exiting."
          exit 1
        fi

    - name: Unpublish extension
      env:
        VSCE_PAT: ${{ secrets.MARKETPLACE_TOKEN}}
      run: |
        vsce unpublish ${{ github.event.inputs['extension-id'] }} --force
